### ISSUE TITLE
[BUG] jq: error (at <stdin>:0): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by tom-spalding** [tj-actions/vercel-wait#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

Thank you for the workflow, I like how simple it is to set up. I'm currently getting the following:

```
jq: error (at <stdin>:0): Cannot iterate over null (null)
Warning: Failed to get deployment from: https://api.vercel.com/v6/deployments?projectId=***&limit=100&teamId=***
```

I suppose a `try` will fix the error in https://github.com/tj-actions/vercel-wait/blob/9fe166182b2609e2d701181687a23997a260f433/entrypoint.sh#L19, but maybe there is an extra parameter missing for the endpoint?

I'll post more if I 

### To Reproduce

```
      - uses: tj-actions/vercel-wait@v1
        id: vercel_preview
        with:
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          team-id: ${{ secrets.VERCEL_TEAM_ID }}
          token: ${{ secrets.VERCEL_TOKEN }}
          sha: ${{ github.sha }}
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

no jq error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
