### ISSUE TITLE
[BUG]  Action Timeout Not Resetting After New Commits in PR

### ISSUE THREAD

**Issue by ibm4n** [tj-actions/vercel-wait#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Love this action, so simple!

My issue: The action is set to timeout after 600 seconds. However, i expected that this timeout should reset with each new commit made to an open Pull Request (PR). Unfortunately, this is not happening. The action fails due to the timeout not resetting after new commits.

### To Reproduce

1. Create a new PR or use an existing open PR.
2. Push a commit to this PR and observe the GitHub Action execution.
3. If 600 seconds are over ( in total ), commit again.
4. Notice that the GitHub Action does not reset its timeout counter and fails due to 600 second timeout.

```
  await-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for vercel deployment
        uses: tj-actions/vercel-wait@v1
        id: waitForUrl
        with:
          project-id: ${{ secrets.ID }}
          token: ${{ secrets.VERCEL_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          team-id: teamid
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

The timeout for the GitHub Action should reset with each new commit pushed to an open PR. This means, for each commit, the action should have a fresh 600 seconds to complete its execution.

### Relevant log output

```shell
Error: Deployment did not become ready within the specified timeout of: 600 seconds
Error: Process completed with exit code 1.
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
